"""empty message

Revision ID: ac416eea4e1f
Revises: 529d01a75828
Create Date: 2022-02-16 22:02:56.576269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac416eea4e1f'
down_revision = '529d01a75828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=13), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
